##插件定制 +Q: 1022767672 ##
##插件QQ交流群 863674325 ##

#插件权限 拥有改权限的玩家 不受惩罚影响 #
# PS: 权限节点请勿修改 仅展示告知作用 #
permission: starsdeath.use

# 基础配置
Default:
  ## 默认开启
  enable: true
  ## 经验惩罚
  Exp:
    ## 默认关闭
    enable: false
    ## 扣除等级的百分比 (1 - 100)  1代表 1% ##
    ## 计算公式 重生后的等级 = 重生前的等级 - 重生前的等级*1% ##
    expPercent: 20
    ## 剩余多少等级 不再扣除 ##
    expLeft: 10
    ## 语言提示
    ### 重生后等级扣除提示
    message1: "§a您受到 §d诅咒巫师 §a的影响 扣除当前等级的 §420%"
    ### 等级不足提示
    message2: "§a您的等级不足,§b天道已为你免除 §d诅咒巫师 §a的影响"
  ## 经验惩罚 ##
  Money:
    ## 默认关闭 ##
    enable: false
    ## 金币扣除 取整数值 100 代表 100 金币 ##
    moneyPercent: 1000
    ## 剩余多少金币 不再扣除 ##
    moneyLeft: 100
    ## 语言提示 ##
    ### 重生后金币扣除提示 ###
    message1: "§a您受到 §d诅咒魔法师 §a的影响，扣除金币 §420 §a个 "
    ### 金币不足提示
    message2: "§a您的金币不足，§b天道已为你免除 §d诅咒巫师 §a的影响"
  worlds:
    - world
    - world_nether
    - world_the_end

